theme: jekyll-theme-dinky
title: Matthew Craghead
description: I'm a systems engineer, musician, thinker, and fun-haver in Portland, Oregon. Check out what I've been up to, send me a message, or buy me a coffee! Thanks for stopping by :)
url: 'https://mattcrag.com'

google_analytics: 'G-LNLR93WGLJ'

instagram:
  username: mattcrag

avatar: https://avatars.githubusercontent.com/u/175430061
